#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("IEMHRDroidApp.Resource", IsApplication=true)]

namespace IEMHRDroidApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_up = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ButtonSignInStyle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ButtonSignUpStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int edit_text_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int ic_action_overflow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int mail = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int monoandroidsplash = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ProgressBarStyle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int xs = 2130837512;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080003
			public const int btnDialogEmail = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int btnSignIn = 2131230727;
			
			// aapt resource value: 0x7f080009
			public const int btnSignUp = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int item_subtitle = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int item_title = 2131230732;
			
			// aapt resource value: 0x7f08000f
			public const int menu = 2131230735;
			
			// aapt resource value: 0x7f08000a
			public const int progressBar1 = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int sample_content_fragment = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int sample_main_layout = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int sliding_tabs = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int txtCreateAccount = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int txtEmail = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int txtFirstName = 2131230720;
			
			// aapt resource value: 0x7f080008
			public const int txtOr = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int txtPassword = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int viewpager = 2131230725;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int dialog_sign_up = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_sample = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int pager_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Tab = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int actionbar_main = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int sample_hide_log = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int sample_show_log = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060002
			public const int CustomActionBarTheme = 2131099650;
			
			// aapt resource value: 0x7f060001
			public const int Mono_Android_Theme_Splash = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int MyActionBar = 2131099651;
			
			// aapt resource value: 0x7f060000
			public const int dialog_animation = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
